name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install pipenv
        run: pip install pipenv
      - name: Install Python dependencies
        run: pipenv install -r hello_world/requirements.txt
      - name: Run Unit Tests
        run: pipenv run pytest
