name: github-action-sam-demo
on:
  push:
    branches: [ main ]

jobs:
  sam-deploy-pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Configure AWS credential
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: SAM Validate
        run: sam validate
      - name: SAM Build
        run: sam build
      - name: Install pipenv
        run: pip install pipenv
      - name: Install Python dependencies
        run: pipenv install -r hello_world/requirements.txt
      - name: Run Unit Tests
        run: pipenv run pytest
      - name: SAM Package
        run: sam package --s3-bucket yimeng-test-bucket1 --output-template-file package.yaml
      - name: SAM Deploy
        run: sam deploy --template-file package.yaml --stack-name githubActionDemo --capabilities CAPABILITY_IAM
