name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies with pipenv
        run: pip install pipenv
      - name: Enter the pipenv
        run: pipenv shell
             pip install -r hello_world/requirements.txt